# Generated by Django 2.0.2 on 2020-09-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200917_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglist',
            name='pub_date',
        ),
    ]
