# Generated by Django 2.2.14 on 2020-08-06 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 7, 3, 54, 1, 219036)),
        ),
    ]
