# Generated by Django 2.0.2 on 2020-05-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usser',
        ),
    ]
