# Generated by Django 2.0.2 on 2020-05-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200515_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usser',
        ),
    ]
