# Generated by Django 2.2.14 on 2020-08-06 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 7, 4, 49, 44, 462283))),
                ('body', models.TextField(default='start writing here')),
            ],
        ),
    ]
